//部门
export const APP_Data =[
  {
    id:1,
    name:"房产建筑部",
    charge:'主营房产、建筑案件纠纷',
    description:'成立于xxxx年，部门共xxx人，成功案例xx件，部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍',
    img:'',
    member:[{
      id:'1',
      name:'刘国田'
    },{
      id:'2',
      name:'李尾芹'
    },{
      id:'3',
      name:'江峰'
    }]
  },
  {
    id:2,
    name:"刑事辩护部",
    charge:'主营刑事、辩护案件纠纷',
    description:'成立于xxxx年，部门共xxx人，成功案例xx件，部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍',
    img:'',
    member:[{
      id:'1',
      name:'刘国田'
    },{
      id:'2',
      name:'李尾芹'
    },{
      id:'3',
      name:'江峰'
    }]
  },
  {
    id:3,
    name:"交通事故部",
    charge:'主营交通事故案件纠纷',
    description:'成立于xxxx年，部门共xxx人，成功案例xx件，部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍',
    img:'',
    member:[{
      id:'1',
      name:'刘国田'
    },{
      id:'2',
      name:'李尾芹'
    },{
      id:'3',
      name:'江峰'
    }]
  },
  {
    id:4,
    name:"公司合同部",
    charge:'主营公司合同案件纠纷',
    description:'成立于xxxx年，部门共xxx人，成功案例xx件，部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍',
    img:'',
    member:[{
      id:'1',
      name:'刘国田'
    },{
      id:'2',
      name:'李尾芹'
    },{
      id:'3',
      name:'江峰'
    }]
  },
  {
    id:5,
    name:"借贷侵权部",
    charge:'主营借贷、侵权案件纠纷',
    description:'成立于xxxx年，成立于xxxx年部门共xxx人，成功案例xx件，部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍',
    img:'',
    member:[{
      id:'1',
      name:'刘国田'
    },{
      id:'2',
      name:'李尾芹'
    },{
      id:'3',
      name:'江峰'
    }]
  },
  {
    id:6,
    name:"婚姻继承部",
    charge:'主营婚姻、继承案件纠纷',
    description:'成立于xxxx年，成立于xxxx部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍',
    img:'',
    member:[{
      id:'1',
      name:'刘国田'
    },{
      id:'2',
      name:'李尾芹'
    },{
      id:'3',
      name:'江峰'
    }]
  },
  {
    id:7,
    name:"金融保险部",
    charge:'主营金融保险案件纠纷',
    description:'成立于xxxx年，成立于xxxx部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍',
    img:'',
    member:[{
      id:'1',
      name:'刘国田'
    },{
      id:'2',
      name:'李尾芹'
    },{
      id:'3',
      name:'江峰'
    }]
  },
  {
    id:8,
    name:"知识产权部",
    charge:'主营房产、建筑案件纠纷',
    description:'成立于xxxx年，部门共xxx人，成功案例xx件，部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍部门介绍',
    img:'',
    member:[{
      id:'1',
      name:'刘国田'
    },{
      id:'2',
      name:'李尾芹'
    },{
      id:'3',
      name:'江峰'
    }]
  },
  {
    id:9,
    name:"医疗海事部",
    member:[{
      id:'1',
      name:'刘国田'
    },{
      id:'2',
      name:'李尾芹'
    },{
      id:'3',
      name:'江峰'
    }]
  },
]
